### ISSUE TITLE
Switch from httparty to faraday

### ISSUE THREAD

**Issue by aaronklaassen** [CrewLabs/unsplash_rb#1]
Already depending on oauth2 gem, which in turn already uses faraday.

**Comment by lukechesser** [comment]
Where do we use `httparty`?

**Comment by aaronklaassen** [comment]
This is the api client - I put this issue here to remind me to do this later.

**Comment by lukechesser** [comment]
OHHH, sorry, thought this was in the main unsplash.com repo. MY BAD
